#!/bin/bash
# tsfc - time since first command
function display_time {
	local T="$1"
	local D="$((T/60/60/24))"
	local H="$((T/60/60%24))"
	local M="$((T/60%60))"
	local S="$((T%60))"
	
	(( $D > 0 )) && printf '%d days, ' $D
	(( $H > 0)) && printf '%d hours, ' $H
	(( $M > 0)) && printf '%d minutes, ' $M
	(( $D > 0 || $H > 0 || $M > 0)) && printf 'and '
	printf '%d seconds\n' $S
}

first="$(awk -F: 'NR==1{print $2}' ~/.zsh_history | tr -d ' ')"
now="$(date +'%s')"
difference=$((now - first))

display_time $difference
